version: '3.8'

services:
  api:
    build: .
    container_name: bigdata_api
    ports:
      - "8000:8000"
    environment:
      - CLASSIFICATION_MODEL_PATH=/app/data/processed/classification_model.joblib
      - REGRESSION_MODEL_PATH=/app/data/processed/regression_model.joblib
      - SCALER_PATH=/app/data/processed/scaler.joblib
      - NUMERIC_FEATURES_PATH=/app/data/processed/numeric_features.joblib
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - bigdata_net
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: bigdata_mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./data:/app/data
    ports:
      - "5000:5000"
    networks:
      - bigdata_net
    restart: unless-stopped

networks:
  bigdata_net:
    driver: bridge
